In [ ]:
!nvidia-smi

Fri May 28 10:15:32 2021       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 465.19.01    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   61C    P8    12W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [ ]:
!apt install libcudnn8 --allow-change-held-packages

Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
The following additional packages will be installed:
  libcudnn8-dev
The following held packages will be changed:
  libcudnn8
The following packages will be upgraded:
  libcudnn8 libcudnn8-dev
2 upgraded, 0 newly installed, 0 to remove and 32 not upgraded.
Need to get 1,037 MB of archives.
After this operation, 340 MB of additional disk space will be used.
Get:1 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  libcudnn8-dev 8.2.0.53-1+cuda11.3 [582 MB]
Get:2 https://developer.download.nvidia.com/compute/cuda/repos/ubuntu1804/x86_64  libcudnn8 8.2.0.53-1+cuda11.3 [454 MB]
Fetched 1,037 MB in 19s (55.6 MB/s)
(Reading database ... 160706 files and directories currently installed.)
Preparing to unpack .../libcudnn8-dev_8.2.0.53-1+cuda11

In [ ]:
%pip install -q tensorflow-addons[tensorflow]
%pip install -q simpleitk
# %pip install -q colab_ssh
%pip install -q wandb

In [ ]:
!gdown https://drive.google.com/uc?id=1jYb-dKqywLm5bQ5esP6YSV5xuBzqBPqm

Downloading...
From: https://drive.google.com/uc?id=1jYb-dKqywLm5bQ5esP6YSV5xuBzqBPqm
To: /content/BRATS_Dataset.tar.gz
2.76GB [00:18, 152MB/s]


In [ ]:
!apt -qq install pigz

In [ ]:
!pigz -dc BRATS_Dataset.tar.gz | tar xf -

In [ ]:
!rm BRATS_Dataset.tar.gz

In [ ]:
%cd /content
!rm -rf 3D_res_attn_Unet

In [ ]:
!git clone https://github.com/ShivamShrirao/3D_res_attn_Unet

In [ ]:
%cd 3D_res_attn_Unet

In [ ]:
%load_ext tensorboard
%load_ext autoreload
%autoreload 2

In [ ]:
import SimpleITK as sitk

In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
import tensorflow_addons as tfa
import numpy as np
import matplotlib.pyplot as plt
import PIL.Image
import glob
from tqdm.notebook import tqdm
from time import time
%matplotlib inline

In [ ]:
from tensorflow.keras.mixed_precision import experimental as mixed_precision
policy = mixed_precision.Policy('mixed_float16')
mixed_precision.set_policy(policy)

Your GPU may run slowly with dtype policy mixed_float16 because it does not have compute capability of at least 7.0. Your GPU:
  Tesla P100-PCIE-16GB, compute capability 6.0
See https://developer.nvidia.com/cuda-gpus for a list of GPUs and their compute capabilities.
If you will use compatible GPU(s) not attached to this host, e.g. by running a multi-worker model, you can ignore this warning. This message will only be logged once
Instructions for updating:
Use tf.keras.mixed_precision.LossScaleOptimizer instead. LossScaleOptimizer now has all the functionality of DynamicLossScale


In [ ]:
def get_data_paths(dataset_path):
    t1 = glob.glob(dataset_path+'/*GG/*/*t1.nii.gz')
    t2 = glob.glob(dataset_path+'/*GG/*/*t2.nii.gz')
    t1ce = glob.glob(dataset_path+'/*GG/*/*t1ce.nii.gz')
    flair = glob.glob(dataset_path+'/*GG/*/*flair.nii.gz')
    seg = glob.glob(dataset_path+'/*GG/*/*seg.nii.gz')
    return list(zip(t1, t2, t1ce, flair, seg))

In [ ]:
train_paths = get_data_paths('../BRATS_Dataset/brats_dataset/')
val_paths = get_data_paths('../BRATS_Dataset/brats_test_dataset/')

In [ ]:
len(train_paths), len(val_paths)

(285, 50)

In [ ]:
from model.preprocess_brats import *

In [ ]:
mean = tf.constant([-0.7050362 , -0.76629126, -0.8043347 , -0.77532315], shape=(1, 4, 1, 1, 1))
std  = tf.constant([0.40932664, 0.33403134, 0.26365048, 0.31701902], shape=(1, 4, 1, 1, 1))

In [ ]:
# mean = 0
# std = 0
# for i, (img,lbl) in tqdm(enumerate(train_ds)):
#     if i == 200//BATCH_SIZE:
#         break
#     mean+= tf.reduce_mean(img, axis=[0,2,3,4])
#     std += tf.math.reduce_std(img, axis=[0,2,3,4])
# mean = tf.reshape(mean/i, (1, 4, 1, 1, 1))
# std = tf.reshape(std/i, (1, 4, 1, 1, 1))

In [ ]:
depth = 128 # 155
height = 192 # 240
width = 160 # 240
(155-depth, 240-height, 240-width)

(27, 48, 80)

In [ ]:
def random_crop3D(imgs, lbls, train=True):          # Crops image to size (128, 192, 160)
    d_cr, h_cr, w_cr = 13, 24, 40
    if train:
        if tf.random.uniform([], 0, 1, dtype=tf.float32) <= 0.8:
            d_cr = tf.random.uniform([], 0, 27, dtype=tf.int32)
            h_cr = tf.random.uniform([], 0, 48, dtype=tf.int32)
            w_cr = tf.random.uniform([], 0, 80, dtype=tf.int32)
    imgs = imgs[:, :, d_cr:d_cr+depth, h_cr:h_cr+height, w_cr:w_cr+width]
    lbls = lbls[:, :, d_cr:d_cr+depth, h_cr:h_cr+height, w_cr:w_cr+width]
    return imgs, lbls

In [ ]:
def final_augmentation(imgs, lbls, train=True):       # input imgs[B, 4, 155, 240, 240], output[B, 4, 128, 192, 160]
    imgs, lbls = random_crop3D(imgs, lbls, train)
    if train:
        if tf.random.uniform([], 0, 1, dtype=tf.float32) <= 0.8:
            imgs = tf.image.random_brightness(imgs, 0.2)      # source code checked, it's fine for 3D
    # imgs = tf.image.per_image_standardization(imgs)   # source code checked, it's fine for 3D
    # imgs = (imgs - mean) / std
    return imgs, lbls

In [ ]:
BATCH_SIZE = 2
AUTOTUNE = tf.data.experimental.AUTOTUNE

In [ ]:
def get_tfds(data_paths, train=False):
    # 53.3373920917511 s
    dataset = tf.data.Dataset.from_tensor_slices(data_paths)
    if train:
        dataset = dataset.shuffle(len(data_paths))
    dataset = dataset.map(load_paths_wrapper, num_parallel_calls=AUTOTUNE)
    # if train:
    #     dataset = dataset.map(random_rotate3D, num_parallel_calls=AUTOTUNE)
    dataset = dataset.repeat()
    dataset = dataset.batch(BATCH_SIZE)
    if train:
        dataset = dataset.map(random_flip3D, num_parallel_calls=AUTOTUNE)
    dataset = dataset.map(lambda x,y: final_augmentation(x,y,train), num_parallel_calls=AUTOTUNE)      # remove for test,val
    dataset = dataset.prefetch(AUTOTUNE)
    return dataset

In [ ]:
train_ds = get_tfds(train_paths, train=True)
val_ds = get_tfds(val_paths)

In [ ]:
import wandb
from wandb.keras import WandbCallback

In [ ]:
wandb.login()

wandb: Currently logged in as: shivamshrirao (use `wandb login --relogin` to force relogin)


True

In [ ]:
config_defaults = {
    'activation'            : 'elu', # swish, elu
    'batch_size'            : BATCH_SIZE,
    'block_type'            : 'AttnBottleneckBlock',
    'clr_step_size'         : 100,      # start from between with big step in one cycle
    'clr_offset_ep'         : 85,
    # 'downsample'            : 'average_pool',
    'groups'                : 'max',
    'dp_rate'               : 0.22,
    'dropout_type'          : 'Spatial',
    'frac_dv'               : 0,
    'loss_function'         : 'FocalTversky',
    'max_lr'                : 8e-4,
    'min_lr'                : 1e-6,
    'nheads'                : 8,
    'norm'                  : 'gn',
    'optimizer'             : 'adamw',
    'weight_decay'          : 2e-5,     # max weight decay
    'z_notes'               : ['kernel size 5 input','removed random rotation', '-1 to 1 imgs','removed z score norm']
}
CONFIG = config_defaults

In [ ]:
# run = wandb.init(id='ok1t1mkm', project="3D_res_attn_Unet", resume='must')
# CONFIG = run.config

wandb: wandb version 0.10.31 is available!  To upgrade, please run:
wandb:  $ pip install wandb --upgrade


In [ ]:
run = wandb.init(project="3D_res_attn_Unet", entity="shivamshrirao", config=config_defaults)
CONFIG = wandb.config

In [ ]:
mean.numpy().ravel(), std.numpy().ravel()

(array([-0.7050362 , -0.76629126, -0.8043347 , -0.77532315], dtype=float32),
 array([0.40932664, 0.33403134, 0.26365048, 0.31701902], dtype=float32))

In [ ]:
tf.keras.backend.set_image_data_format('channels_first')

In [ ]:
## attention shortcuts to be used.
## try attention on the unet shortcuts
## try Global Context Block
## try input image pyramid and deep supervised output layers (output from intermediate layers (fuse with conv-sigmoid like U^2net ??))
## TRY PIXELSHUFFLE
## Try SPARSE CONV NET https://github.com/facebookresearch/SparseConvNet

In [ ]:
from model.conv_blocks import *

In [ ]:
def enc_dec(x, block, frac_dv, stack_args):     # x(64,64,96,80)
    x1 = down_stack(x ,  64, nblocks=2, block=block, strides=2, **stack_args)     # (256,32,48,40)
    x2 = down_stack(x1, 128, nblocks=2, block=block, strides=2, **stack_args)     # (512,16,24,20)
    x3 = down_stack(x2, 256, nblocks=2, block=block, strides=2, frac_dv=frac_dv, **stack_args) # (1024, 8,12,10)
    x4 = down_stack(x3, 256, nblocks=3, block=block, strides=2, frac_dv=frac_dv, **stack_args) # (1024, 4, 6, 5)

    y = up_stack(x4,x3, 128, nblocks=3, block=block, strides=2, frac_dv=frac_dv, **stack_args) # (1024+1024->512,8,12,10)
    y = up_stack(y, x2,  64, nblocks=2, block=block, strides=2, **stack_args)     # (512+512->256,16,24,20)
    y = up_stack(y, x1,  32, nblocks=2, block=block, strides=2, **stack_args)     # (256+256->128,32,48,40)
    y = up_stack(y, x ,  16, nblocks=1, block=block, strides=2, **stack_args)     # (128+ 64-> 64,64,96,80)
    return y


def build_network(cfg, block, input_shape=(4,128,192,160), classes=4):
    stack_args = {'activation': cfg['activation'], 'groups': cfg['groups'], 'norm': cfg['norm'],
                  'dp_rate': cfg['dp_rate'], 'dropout_type': cfg['dropout_type']}

    inp = layers.Input(shape=input_shape)                           # ( 4,128,192,160)
    x = inp
    x = ConvNorm(32, kernel_size=5, strides=2, activation=cfg['activation'], norm=cfg['norm'])(x)   # (32,64,96,80)
    x = ConvNorm(64, kernel_size=3, do_norm_act=False)(x)                               # (64, 64, 96, 80)

    x = enc_dec(x, block, cfg['frac_dv'], stack_args)                                   # (64, 64, 96, 80)

    x = NormAct(activation=cfg['activation'], norm=cfg['norm'])(x)
    x = layers.UpSampling3D(data_format="channels_first")(x)                            # (64,128,192,160)
    x = ConvNorm(16, kernel_size=5, activation=cfg['activation'], norm=cfg['norm'])(x)  # (16,128,192,160)
    x = ConvNorm(classes, kernel_size=3, do_norm_act=False)(x)                          #(3,128,192,160)
    x = layers.Softmax(axis=1)(x)         # softmax cause each pixel has unique class, no overlap with other classes, verified.

    return tf.keras.Model(inputs=inp, outputs=x)

In [ ]:
block = AttnBottleneckBlock
CONFIG['block_type'] = block.__name__
model = build_network(CONFIG, block, input_shape=(4,depth,height,width), classes=4)

In [ ]:
model.summary()

Model: "model_1"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
input_19 (InputLayer)           [(None, 4, 128, 192, 0                                            
__________________________________________________________________________________________________
conv_norm_4_1 (ConvNorm)        (None, 32, 64, 96, 8 16064       input_19[0][0]                   
__________________________________________________________________________________________________
conv_norm_5_1 (ConvNorm)        (None, 64, 64, 96, 8 55360       conv_norm_4_1[0][0]              
__________________________________________________________________________________________________
attn_bottleneck_block_17 (AttnB (None, 256, 32, 48,  41616       conv_norm_5_1[0][0]              
____________________________________________________________________________________________

In [ ]:
model_plot = tf.keras.utils.plot_model(model, '/content/model.png', show_shapes=True, dpi=None)

In [ ]:
wandb.log({"model": wandb.Image("/content/model.png")})

In [ ]:
from tensorflow.python.client import session
from tensorflow.python.summary import summary

In [ ]:
log_dir = run.dir+"/trace_log"
!rm -rf $log_dir

@tf.function
def trace(x):
    return model(x)

data = tf.random.normal((2,) + model.input_shape[1:])
data = tf.constant(data)

imported_g = trace.get_concrete_function(data).graph

# Export the graph
with session.Session(graph=imported_g) as sess:
    pb_visual_writer = summary.FileWriter(log_dir)
    pb_visual_writer.add_graph(sess.graph)

In [ ]:
# %tensorboard --logdir $log_dir

In [ ]:
# from google.colab.output import eval_js
# print(eval_js("google.colab.kernel.proxyPort(6006)"))

In [ ]:
import gc
gc.collect()

459

In [ ]:
from model.losses import *
from model.utils import *

In [ ]:
steps_per_epoch = int(np.ceil(len(train_paths)/BATCH_SIZE))

In [ ]:
clr_offset = CONFIG["clr_offset_ep"]*steps_per_epoch
clr = CustomCLR(
        offset=clr_offset,
        initial_learning_rate=CONFIG["min_lr"],
        maximal_learning_rate=CONFIG["max_lr"],
        step_size=CONFIG["clr_step_size"] * steps_per_epoch,
        scale_mode="cycle")

In [ ]:
wdc = CustomCLR(
        offset=clr_offset,
        initial_learning_rate=CONFIG["weight_decay"]*CONFIG["min_lr"]/CONFIG["max_lr"],
        maximal_learning_rate=CONFIG["weight_decay"],
        step_size=CONFIG["clr_step_size"] * steps_per_epoch,
        scale_mode="cycle")

In [ ]:
if CONFIG["optimizer"] == 'adamw':
    opt = tfa.optimizers.AdamW(learning_rate=clr, weight_decay=wdc)
elif CONFIG["optimizer"] == 'adam':            # or just make weight_decay=0
    opt = tf.keras.optimizers.Adam(learning_rate=clr)
opt = tf.keras.mixed_precision.LossScaleOptimizer(opt)

In [ ]:
if CONFIG["loss_function"] == 'FocalTversky':
    loss_function = FocalTversky()
elif CONFIG["loss_function"] == 'cce':
    loss_function = cce

In [ ]:
model.compile(optimizer=opt, loss=loss_function, metrics=[dsc])

In [ ]:
model.save(wandb.run.dir+"/model-best.h5")

In [ ]:
wandb.save("*.h5")

In [ ]:
# model = tf.keras.models.load_model(wandb.restore("model-best.h5").name, custom_objects={'ConvNorm': ConvNorm,
#                                                                                         'NormAct': NormAct,
#                                                                                         'AttnBottleneckBlock': AttnBottleneckBlock,
#                                                                                         'BasicBlock': BasicBlock,
#                                                                                         'InvertedResBlock': InvertedResBlock,
#                                                                                         'SqueezeExcite': SqueezeExcite,
#                                                                                         'MHSA3D': MHSA3D,
#                                                                                         'AbsPosEmb': AbsPosEmb,
#                                                                                         'dsc': dsc,
#                                                                                         'FocalTversky': FocalTversky,
#                                                                                         'CustomCLR': CustomCLR,
#                                                                                         })
# model.compile(optimizer=model.optimizer, loss=model.loss, metrics=[dsc])

In [ ]:
initial_epoch = model.optimizer.iterations//steps_per_epoch
initial_epoch

<tf.Tensor: shape=(), dtype=int64, numpy=88>

In [ ]:
wandb_cb = WandbCallback(monitor='dsc', mode='max')

In [ ]:
class CustomCallback(tf.keras.callbacks.Callback):
    def on_epoch_begin(self, epoch, logs=None):
        img, lbl = next(iter(val_ds))
        pred = self.model(img)
        i = epoch % BATCH_SIZE
        img = img[i,1].numpy()
        mn = img.min()
        mx = img.max()
        img = (img - mn)/(mx - mn) * 255
        lbl = lbl[i,1:].numpy()*255
        pred = pred[i,1:].numpy()*255
        get_gif(img, lbl, pred, "out.gif")
        wandb.log({"Outputs": wandb.Image("out.gif")})
        # model-latest ??
        wandb.save("*.h5")                      # For forcing sync
        gc.collect()

In [ ]:
history = model.fit(train_ds,
                    epochs=100,
                    steps_per_epoch=np.ceil(len(train_paths)/BATCH_SIZE),
                    validation_data=val_ds,
                    validation_steps=np.ceil(len(val_paths)//BATCH_SIZE),
                    initial_epoch=initial_epoch,
                    workers=4,
                    use_multiprocessing=True,
                    callbacks=[CustomCallback(), wandb_cb])

Epoch 89/100
143/143 [==============================] - 687s 4s/step - loss: 0.9475 - dsc: 0.7548 - val_loss: 0.6733 - val_dsc: 0.8383
Epoch 90/100
143/143 [==============================] - 630s 4s/step - loss: 0.9114 - dsc: 0.7654 - val_loss: 0.6324 - val_dsc: 0.8531
Epoch 91/100
143/143 [==============================] - 631s 4s/step - loss: 0.9302 - dsc: 0.7610 - val_loss: 0.6278 - val_dsc: 0.8581
Epoch 92/100
143/143 [==============================] - 630s 4s/step - loss: 0.9175 - dsc: 0.7647 - val_loss: 0.6112 - val_dsc: 0.8573
Epoch 93/100
143/143 [==============================] - 631s 4s/step - loss: 0.9207 - dsc: 0.7633 - val_loss: 0.6455 - val_dsc: 0.8462
Epoch 94/100
143/143 [==============================] - 637s 4s/step - loss: 0.9290 - dsc: 0.7602 - val_loss: 0.6414 - val_dsc: 0.8552
Epoch 95/100
143/143 [==============================] - 637s 4s/step - loss: 0.9492 - dsc: 0.7536 - val_loss: 0.6317 - val_dsc: 0.8523
Epoch 96/100
143/143 [==============================] -

In [ ]:
model.evaluate(val_ds, steps=np.ceil(len(val_paths)//BATCH_SIZE))

25/25 [==============================] - 35s 1s/step - loss: 0.6143 - dsc: 0.8600


[0.6143304705619812, 0.859954297542572]

In [ ]:
scores = []
for i, (a,b) in tqdm(enumerate(train_ds)):
    if i==steps_per_epoch:
        break
    o = model(a)
    o = tf.cast(o, tf.float32)
    scores.append(dsc(b,o))

In [ ]:
np.mean(scores, axis=0)

array([0.7446584 , 0.789903  , 0.79872084], dtype=float32)

In [ ]:
run.finish()